services:
  - type: web
    name: facebook-automation-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://faceautomation.netlify.app
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: facebook-automation-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mypro-kwda.onrender.com
    autoDeploy: true 